# Numpy Basics

In [1]:
# Importing libraries
import numpy as np
import pandas as pd

In [2]:
x = np.array([1,2,3,5]) # creating numpy array
y = np.array((3,4,5,7))

print("x:", x)
print("Type:", type(x))
print("Length:", len(x))

print("y:", y)
print("Type:", type(y))
print("Length:", len(y))

x: [1 2 3 5]
Type: <class 'numpy.ndarray'>
Length: 4
y: [3 4 5 7]
Type: <class 'numpy.ndarray'>
Length: 4


In [3]:
x = np.ones((3,4), dtype=np.int16) #(3,4) specifies rows and columns respectively; np.int16 specifies type to be considered
print("x:", x)

y = np.full((3,4), 0.55) # #(3,4) specifies rows and columns respectively; 0.55 is the value to be filled in each cell
print("y:", y)


x: [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
y: [[0.55 0.55 0.55 0.55]
 [0.55 0.55 0.55 0.55]
 [0.55 0.55 0.55 0.55]]


In [4]:
x = np.arange(10, 30, 5) # array of numbers between 10 to 30 excluding 30 with common difference of 5
y = np.arange(0, 2, 0.3) # array of numbers between 0 to 2 excluding 2 with common difference of 0.3

print("x:",x)
print("y:",y)


z = np.linspace(10, 30, 6) # array of numbers between 10 and 30 both inclusive, having equal interval and 6 elements
print("z:",z)

x: [10 15 20 25]
y: [0.  0.3 0.6 0.9 1.2 1.5 1.8]
z: [10. 14. 18. 22. 26. 30.]


In [5]:
x = np.random.rand(2, 3) # creating random numbers in matrix 2x3
y = np.random.rand(4, 5) # creating random numbers in matrix 4x5

print("x:",x)
print("y:",y)

x: [[0.3651584  0.46651371 0.55152962]
 [0.90863042 0.97590174 0.25955376]]
y: [[0.97550032 0.41035827 0.27824471 0.10002972 0.2152555 ]
 [0.44198156 0.55017495 0.70624608 0.95168589 0.27740936]
 [0.15503399 0.53145769 0.34063017 0.66873114 0.63150116]
 [0.36727536 0.82318919 0.69502734 0.703161   0.3352282 ]]


In [6]:
# Creating two normal distributions

mu, sigma = 0, 1
x = np.random.normal(mu, sigma, 50) # creating 50 random samples from normal distribution with mu=0, sd=1
y = np.random.normal(50, 0.1, 50)
print(x)
print(y)

print("\nMean of x:", np.mean(x))
print("Std. Deviation of x:",np.std(x))

[ 1.3802849   1.06443489  0.85464968 -0.96635272 -0.33305721 -0.40540898
  0.06133347 -2.04632767  0.83549686  1.25846284  0.11319099 -0.03451268
 -0.18437363  1.02034902 -0.73966249 -0.33957314  0.61199652  1.27839282
 -0.96719211 -1.23930526  0.33450155  1.69370808  1.50557686 -2.07230358
 -0.54061808  1.70150855  0.07563046 -0.47350841 -2.0955073  -0.18916934
  2.11510431 -1.1280606   0.49717684 -0.64415883  0.00415191 -0.25063182
  1.0994007  -0.40874183  0.22003672 -0.76350536  0.45582853 -0.11315125
  0.26831061  0.94643657  0.61618554 -0.03150158  1.48893278 -0.70881695
 -0.91782258 -0.31585146]
[50.19982443 49.94986259 50.05731499 50.01047392 50.19526073 49.96646468
 49.95369765 49.97789121 50.05691546 49.84178684 50.17808358 49.96775157
 50.00749897 49.94499207 50.04583717 50.01117766 49.93829967 50.01858961
 50.05038817 49.9799127  49.92920233 49.83360523 50.10600757 50.00464601
 50.09481617 50.01037136 50.03987289 49.99481751 50.05949032 49.94758875
 49.98059891 49.85791399 

In [7]:
np.corrcoef(x, y) # Correlation matrix

array([[1.        , 0.07097451],
       [0.07097451, 1.        ]])

In [8]:
import random
random.seed(2333) # seed will help to set same values of random

In [9]:
y = np.random.normal(mu, sigma, 100)

print(np.mean(y))
print(np.std(y))

0.017140921122087052
0.9822815385992552


In [10]:
y = np.random.normal(mu, sigma, 200)

print(np.mean(y))
print(np.std(y))

-0.05945665203039562
0.9833290745986839


In [11]:
y = np.random.normal(mu, sigma, 500)

print(np.mean(y))
print(np.std(y))

-0.015469404279882571
0.985559300339877


In [12]:
y = np.random.normal(mu, sigma, 1000) # As no. of samples are increasing, mean and sd are tending toward 0 and 1 resp.

print(np.mean(y))
print(np.std(y))

-0.0008912064684190741
0.9862148673323282


In [13]:
# Some Functions and Methods

y = np.array([[3,4,5,7,10,12,13,15], [1,2,3,4,5,6,7,8]])

print(y)
print("Ndim:", np.ndim(y))
print("Shape:", y.shape)
print("Size:", y.size)
print("Dtype:", y.dtype)
print("Itemsize:", y.itemsize)
print("Reshape:", y.reshape(4, 4)) # changing shape to 4x4

[[ 3  4  5  7 10 12 13 15]
 [ 1  2  3  4  5  6  7  8]]
Ndim: 2
Shape: (2, 8)
Size: 16
Dtype: int64
Itemsize: 8
Reshape: [[ 3  4  5  7]
 [10 12 13 15]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [14]:
# Extracting elements
y = np.array([1,2,3,4,5])

print(y[2:5]) # prints items 2 to 4
print(y[2::2]) # prints items 2 to end skipping 2 items
print(y[::-1]) # prints the array in the reverse order
print(y[1:]) # prints from row 1 to end

# These are quiet similar to lists

[3 4 5]
[3 5]
[5 4 3 2 1]
[2 3 4 5]


In [15]:
# Some Basic Vector and Matrix Multiplication operations

print("Some Basic Vector operations--\n")
x = np.array([1,2,3,4,5])
y = np.array([1,3,5,7,9])

print("x", x)
print("y", y)

print("Addition of 2 vectors:", x+y)
print("Subtraction of 2 vectors:", x-y)
print("Multiplication of 2 vectors:", x*y)
print("Division of 2 vectors:", x/y)
print("Mod of 2 vectors:", x%y)

print()
print()

print("Some Basic Matrix Operations--\n")
a = np.array([[1,2],[3,4]])
b = np.array([[1,3],[5,7]])

print("a:\n", a)
print("b:\n", b)

print("Addition of 2 matrices:\n", a+b)
print("Subtraction of 2 matrices:\n", a-b)
print("Division of 2 matrices:\n", a/b)
print("Mod of 2 matrices:\n", a%b)
print("Multiplication of 2 matrices:\n", a*b)
print("Dot product multiplication:\n", np.dot(a, b)) # here no. of columns of a should be equal to no. of rows of b
print("Transpose:\n", np.transpose(a))
print("A square:\n", np.dot(a, np.transpose(a)))



Some Basic Vector operations--

x [1 2 3 4 5]
y [1 3 5 7 9]
Addition of 2 vectors: [ 2  5  8 11 14]
Subtraction of 2 vectors: [ 0 -1 -2 -3 -4]
Multiplication of 2 vectors: [ 1  6 15 28 45]
Division of 2 vectors: [1.         0.66666667 0.6        0.57142857 0.55555556]
Mod of 2 vectors: [0 2 3 4 5]


Some Basic Matrix Operations--

a:
 [[1 2]
 [3 4]]
b:
 [[1 3]
 [5 7]]
Addition of 2 matrices:
 [[ 2  5]
 [ 8 11]]
Subtraction of 2 matrices:
 [[ 0 -1]
 [-2 -3]]
Division of 2 matrices:
 [[1.         0.66666667]
 [0.6        0.57142857]]
Mod of 2 matrices:
 [[0 2]
 [3 4]]
Multiplication of 2 matrices:
 [[ 1  6]
 [15 28]]
Dot product multiplication:
 [[11 17]
 [23 37]]
Transpose:
 [[1 3]
 [2 4]]
A square:
 [[ 5 11]
 [11 25]]
