# Numpy Basics

In [1]:
# Importing libraries
import numpy as np
import pandas as pd

In [5]:
x = np.array([1,2,3,5]) # creating numpy array
y = np.array((3,4,5,7))

print("x:", x)
print("Type:", type(x))
print("Length:", len(x))

print("y:", y)
print("Type:", type(y))
print("Length:", len(y))

x: [1 2 3 5]
Type: <class 'numpy.ndarray'>
Length: 4
y: [3 4 5 7]
Type: <class 'numpy.ndarray'>
Length: 4


In [4]:
x = np.ones((3,4), dtype=np.int16) #(3,4) specifies rows and columns respectively; np.int16 specifies type to be considered
print("x:", x)

y = np.full((3,4), 0.55) # #(3,4) specifies rows and columns respectively; 0.55 is the value to be filled in each cell
print("y:", y)


x: [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
y: [[0.55 0.55 0.55 0.55]
 [0.55 0.55 0.55 0.55]
 [0.55 0.55 0.55 0.55]]


In [8]:
x = np.arange(10, 30, 5) # array of numbers between 10 to 30 excluding 30 with common difference of 5
y = np.arange(0, 2, 0.3) # array of numbers between 0 to 2 excluding 2 with common difference of 0.3

print("x:",x)
print("y:",y)


z = np.linspace(10, 30, 6) # array of numbers between 10 and 30 both inclusive, having equal interval and 6 elements
print("z:",z)

x: [10 15 20 25]
y: [0.  0.3 0.6 0.9 1.2 1.5 1.8]
z: [10. 14. 18. 22. 26. 30.]


In [11]:
x = np.random.rand(2, 3) # creating random numbers in matrix 2x3
y = np.random.rand(4, 5) # creating random numbers in matrix 4x5

print("x:",x)
print("y:",y)

x: [[0.65689625 0.00977458 0.30884681]
 [0.62870434 0.12775691 0.79799402]]
y: [[0.98605382 0.99834735 0.76045641 0.85579514 0.77900182]
 [0.53716083 0.97947912 0.62821365 0.91114154 0.39402217]
 [0.04493369 0.22537367 0.41561955 0.3646907  0.04975886]
 [0.73173486 0.17421562 0.2429176  0.87279351 0.16846284]]


In [13]:
# Creating two normal distributions

mu, sigma = 0, 1
x = np.random.normal(mu, sigma, 50) # creating 50 random samples from normal distribution with mu=0, sd=1
y = np.random.normal(50, 0.1, 50)
print(x)
print(y)

print("\nMean of x:", np.mean(x))
print("Std. Deviation of x:",np.std(x))

[-0.02720375 -0.34479225  0.1775796   0.02804569 -1.60213019  1.56110153
  1.66166627  0.07117159  1.27930436  0.10671668 -1.2789991   0.13322498
 -0.2013692  -1.49415104  2.07277884  1.32131406 -0.38996781  0.14529508
  0.51477604  1.27293215 -0.93954265 -1.19269559 -0.98789454  0.67187914
  1.31098726  1.68340881 -1.66115235  1.22479911 -1.81789939  1.32870453
  0.07065787 -1.56501351  0.02060607  0.25944082  0.56174383  0.73548189
  0.58017051  1.85019568  0.03677284  0.48652502 -0.82192387  1.17723059
 -1.19657229  1.49919192  0.69861572 -0.30476539  0.67102634  0.82253515
 -0.49206637  0.73415552]
[50.15139542 49.99421577 49.9002867  50.193415   49.89720745 50.14166717
 50.09543819 49.84369186 49.92664757 50.09071821 49.9315917  50.09892726
 50.03389711 49.86621815 49.97421218 50.10688072 49.93932819 50.02111026
 50.27434908 50.09420091 49.97954398 49.95511924 50.00624072 49.87728123
 50.03877512 49.83641823 50.14900326 50.13090853 50.01701447 50.16051747
 50.01959982 50.12347701 

In [16]:
np.corrcoef(x, y) # Correlation matrix

array([[1.        , 0.14123901],
       [0.14123901, 1.        ]])

In [15]:
import random
random.seed(2333) # seed will help to set same values of random

In [ ]:
y = np.random.normal(mu, sigma, 100)

print(np.mean(y))
print(np.std(y))

array([-0.38691969, -0.73852241,  0.64254636, -1.01378718, -1.27590054,
       -0.51195186,  0.56150086, -0.88508516,  0.34912764, -0.72959025,
        0.27757774,  2.49995762, -0.8269146 ,  0.21794962,  0.22395765,
       -0.55327928,  0.42754409,  1.42594389, -0.59667229, -3.00104212,
       -1.51520975,  1.06679562,  0.15350108, -1.01180916,  0.07016624,
       -0.63957112,  1.52322512, -1.35193952, -1.07937971, -3.12203478,
        0.61789598, -0.69052832,  0.29532367,  0.5367032 , -0.72996759,
        1.63791893,  0.25010752, -0.46834661, -0.11320872, -0.80674335,
        1.31837498, -0.38221096,  0.21921103, -1.46622964, -0.95482278,
       -0.12642401,  1.24461299,  0.5197576 ,  0.65578867,  1.41334291,
       -0.05222002, -0.39743224,  0.01895837,  1.19684284, -1.38048125,
       -0.08716464, -1.1504026 ,  0.32983682, -1.20643242,  0.91158104,
        1.39372855,  0.36933887, -0.01421518,  0.39414346, -1.08522005,
        0.950667  , -0.5474053 ,  0.19696355,  0.35869154, -0.12

In [ ]:
y = np.random.normal(mu, sigma, 200)

print(np.mean(y))
print(np.std(y))

-0.05028261048021287
0.9515817412683031


In [ ]:
y = np.random.normal(mu, sigma, 500)

print(np.mean(y))
print(np.std(y))

0.010444486998970284
0.998815011740111


In [ ]:
y = np.random.normal(mu, sigma, 1000) # As no. of samples are increasing, mean and sd are tending toward 0 and 1 resp.

print(np.mean(y))
print(np.std(y))

-0.005215409679478989
1.0168717137471066


In [25]:
# Some Functions and Methods

y = np.array([[3,4,5,7,10,12,13,15], [1,2,3,4,5,6,7,8]])

print(y)
print("Ndim:", np.ndim(y))
print("Shape:", y.shape)
print("Size:", y.size)
print("Dtype:", y.dtype)
print("Itemsize:", y.itemsize)
print("Reshape:", y.reshape(4, 4)) # changing shape to 4x4

[[ 3  4  5  7 10 12 13 15]
 [ 1  2  3  4  5  6  7  8]]
Ndim: 2
Shape: (2, 8)
Size: 16
Dtype: int64
Itemsize: 8
Reshape: [[ 3  4  5  7]
 [10 12 13 15]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [26]:
# Extracting elements
y = np.array([1,2,3,4,5])

print(y[2:5]) # prints items 2 to 4
print(y[2::2]) # prints items 2 to end skipping 2 items
print(y[::-1]) # prints the array in the reverse order
print(y[1:]) # prints from row 1 to end

# These are quiet similar to lists

[3 4 5]
[3 5]
[5 4 3 2 1]
[2 3 4 5]


In [34]:
# Some Basic Vector and Matrix Multiplication operations

print("Some Basic Vector operations--\n")
x = np.array([1,2,3,4,5])
y = np.array([1,3,5,7,9])

print("x", x)
print("y", y)

print("Addition of 2 vectors:", x+y)
print("Subtraction of 2 vectors:", x-y)
print("Multiplication of 2 vectors:", x*y)
print("Division of 2 vectors:", x/y)
print("Mod of 2 vectors:", x%y)

print()
print()

print("Some Basic Matrix Operations--\n")
a = np.array([[1,2],[3,4]])
b = np.array([[1,3],[5,7]])

print("a:\n", a)
print("b:\n", b)

print("Addition of 2 matrices:\n", a+b)
print("Subtraction of 2 matrices:\n", a-b)
print("Division of 2 matrices:\n", a/b)
print("Mod of 2 matrices:\n", a%b)
print("Multiplication of 2 matrices:\n", a*b)
print("Dot product multiplication:\n", np.dot(a, b)) # here no. of columns of a should be equal to no. of rows of b
print("Transpose:\n", np.transpose(a))
print("A square:\n", np.dot(a, np.transpose(a)))



Some Basic Vector operations--

x [1 2 3 4 5]
y [1 3 5 7 9]
Addition of 2 vectors: [ 2  5  8 11 14]
Subtraction of 2 vectors: [ 0 -1 -2 -3 -4]
Multiplication of 2 vectors: [ 1  6 15 28 45]
Division of 2 vectors: [1.         0.66666667 0.6        0.57142857 0.55555556]
Mod of 2 vectors: [0 2 3 4 5]


Some Basic Matrix Operations--

a:
 [[1 2]
 [3 4]]
b:
 [[1 3]
 [5 7]]
Addition of 2 matrices:
 [[ 2  5]
 [ 8 11]]
Subtraction of 2 matrices:
 [[ 0 -1]
 [-2 -3]]
Division of 2 matrices:
 [[1.         0.66666667]
 [0.6        0.57142857]]
Mod of 2 matrices:
 [[0 2]
 [3 4]]
Multiplication of 2 matrices:
 [[ 1  6]
 [15 28]]
Dot product multiplication:
 [[11 17]
 [23 37]]
Transpose:
 [[1 3]
 [2 4]]
A square:
 [[ 5 11]
 [11 25]]
